CREATE TABLE "TAAM_USER" (
    ID UNIQUEIDENTIFIER DEFAULT NewId() PRIMARY KEY,
    USERNAME VARCHAR(50),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(50) UNIQUE ,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_ON DATETIME NOT NULL,
    UPDATED_BY VARCHAR(50),
    UPDATED_ON DATETIME
);